### ISSUE TITLE
Login throttled

### ISSUE THREAD

**Issue by linusnyren** [tillsteinbach/VWsFriend#107]
Hi again!
I figured i would update VWsFriend to get the latest fixes.

But after updating and trying to start the project with the homekit-host i get the following error.
Any ideas
<img width="1436" alt="Skärmavbild 2021-11-29 kl  17 42 30" src="https://user-images.githubusercontent.com/36070811/143908146-12776f14-0896-4de3-9f6d-118840ce7dbd.png">
?

**Comment by linusnyren** [comment]
Just saw that the myconfig.env suddenly resetted to standard values.
It works correctly now.
I didn't pull latest changes with git, only docker.

This is now resolved

**Comment by tillsteinbach** [comment]
The reason is probably that I changed the naming of some variables approx 3 months ago. I did not think enough about users that have had an very early version running. Sorry that this was hitting you!
