### ISSUE TITLE
Updating Docker

### ISSUE THREAD

**Issue by dewoert** [tillsteinbach/VWsFriend#113]
Hello,

I did an update for the 0.10.0 version just now, but i remains at 0.9.5 ?
Docker is running on Synology NAS.
Logging gives 
`2021-12-01T20:27:50+0000:WARNING:vehicle:/vehicles/WVWZZZE1ZMP02                                                   2679: Unknown attribute readinessStatus with value {'connectionState': {'isOnlin                                                   e': True, 'isActive': False, 'batteryPowerLevel': 'comfort', 'dailyPowerBudgetAv                                                   ailable': True}, 'connectionWarning': {'insufficientBatteryLevelWarning': False,                                                    'dailyPowerBudgetWarning': False}}
`
(New status from API ?)

`Versions`
`VWsFriend: 0.9.5`
`WeConnect Python Library: 0.22.0`
`Database Schema: f6785099280a`
`Database: PostgreSQL 13.5 (Debian 13.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`

I updated with:
`docker-compose pull`
`docker-compose --env-file ./myconfig.env up`
Are the docker files allready updated, or do i have to wait a bit longer ?

**Comment by tillsteinbach** [comment]
Yes, the docker images are still building. I have to check why it takes so long

**Comment by dewoert** [comment]
No problem.
I try later today or tomorrow.
Thanks for the quick reply, and please close this issue.

**Comment by tillsteinbach** [comment]
I think I found the problem. Images should be online in ~ 1 hour

**Comment by dewoert** [comment]
Many thanks, update is succesfull now !

**Comment by tillsteinbach** [comment]
Happy to hear that!
