### ISSUE TITLE
Use existing Grafana installation

### ISSUE THREAD

**Issue by mtjoernelund** [tillsteinbach/VWsFriend#115]
I am not that much into Docker (should be - I know…). I already have Grafana installed on my Raspberry Pi. Can I utilize the already installed Grafana instance with this image? Or does this not make sense?

**Comment by tillsteinbach** [comment]
I would say it is possible with a lot of manual work, But you would need to update to exactly the same version vwsfriend is using. So if you would like to safe some hassle I would recommend running two instances of grafana at the same time. You can change the grafana port with the variable GF_SERVER_HTTP_PORT if you need to.

In general you can use vwsfriend completely without docker by installing everything manually. But you will spend a lot of time updating things in the future.

**Comment by mtjoernelund** [comment]
Thanks for quick feedback. This was kind of expected, but as mentioned very little experience with Docker. Thank you for maintaining this!

**Comment by tillsteinbach** [comment]
One year ago I was kind of in a similar situation. I can just encourage you to give it a try. Docker is quite easy to understand from a user perspective (developing images is another story though). If you managed to natively work on a RPi you won't have any problems. Only think to consider is this: https://github.com/tillsteinbach/VWsFriend#known-issues
