### ISSUE TITLE
no matching manifest for linux/386 in the manifest list entries

### ISSUE THREAD

**Issue by dazzzl** [tillsteinbach/VWsFriend#124]
it seems that this project has no support for linux/386..

any workaround? Thanks!

and yes, my server is an Atom with only 32 bit support....

**Comment by tillsteinbach** [comment]
To the best of my knowledge I cannot add 386 support as my dependencies Ubuntu 21.04 and Grafana do not offer it.

**Comment by dazzzl** [comment]
Ok, thanks. Is there any chance to run VWfreind without docker? Is there any instructions? The pip package could be also not found.

**Comment by tillsteinbach** [comment]
That should be possible. At least parts. What version of python are you running pip with?

**Comment by dazzzl** [comment]
I have 

Python 3.8.5
grafana 7.5.11

**Comment by tillsteinbach** [comment]
hmmm, then you should see it with pip

**Comment by dazzzl** [comment]
pip3 install vwsfriend
ERROR: Could not find a version that satisfies the requirement vwsfriend (from versions: none)
ERROR: No matching distribution found for vwsfriend

**Comment by dazzzl** [comment]
Ok, found the problem Thanks!

pip3 --version
pip 20.2.4 from /usr/lib/python3.6/site-packages/pip (python 3.6)

pip3.8 install vwsfriend works

**Comment by dazzzl** [comment]
ok, vwsfriend works with the .netrc file and I see my car.
Grafana works also and ask me for the login and password... which login and password should I use?
Thanks!

**Comment by tillsteinbach** [comment]
The default is admin/admin

**Comment by dazzzl** [comment]
ok thanks ... however I need a little bit more help...
I installed postgres and added a user vwsfriend 
I first run into the problem that vwfriend could not connect which was solved to change into the pg_hba.conf the access method to md5
now I can connect to the database from vwsfriend and grafana
My question is. how can I import the dashboard? Thanks for you help!

**Comment by tillsteinbach** [comment]
When you put the files in https://github.com/tillsteinbach/VWsFriend/tree/main/grafana (see also `https://grafana.com/docs/grafana/latest/administration/provisioning/`) to the right spots

copy ./config/grafana/provisioning/ to /etc/grafana/provisioning/
copy ./dashboards/ to /var/lib/grafana-static/dashboards/

**Comment by dazzzl** [comment]
Thanks, it works!

**Comment by tillsteinbach** [comment]
Awesome! You are the first one making it work without docker! If you have some time, would you mind to write some words what you did in the wiki for others to be able to follow your path?

**Comment by tillsteinbach** [comment]
yes, sure!

**Comment by dazzzl** [comment]
done.. please check the wiki

**Comment by tillsteinbach** [comment]
This is great! Big thanks!
