### ISSUE TITLE
Problem bei erstinstallation (docker-compose)

### ISSUE THREAD

**Issue by gbmd** [tillsteinbach/VWsFriend#137]
Hi Till,
ich habe den service gerade neu aufgesetzt auf einer frischen VM, jetzt gibt es leider ein Problem bei der Installation...
```
ubuntu@my-vm:~/development/vwsfriend$ curl https://raw.githubuserconten
t.com/tillsteinbach/VWsFriend/main/docker-compose.yml > docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- 100  2404  100  2404    0     0  12328      0 --:--:-- --:--:-- --:--:-- 
ubuntu@my-vm:~/development/vwsfriend$ docker-compose --env-file ./myenv.env up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
Das env-file habe ich heruntergeladen und angepasst, keine Sorge.

Weißt du an der Stelle weiter?
VG

**Comment by gbmd** [comment]
PS: mit Sudo:
```ubuntu@my-vm:~/development/vwsfriend$ sudo docker-compose --env-file ./myenv.env up
ERROR: Invalid interpolation format for "vwsfriend" option in service "services": "tillsteinbach/vwsfriend:${VWSFRIEND_VERSION-latest}"
```

**Comment by tillsteinbach** [comment]
was sagt denn `docker-compose --version`?

**Comment by gbmd** [comment]
docker-compose version 1.25.0, build unknown

geholt über aptitude mit ubuntu 20.04

**Comment by tillsteinbach** [comment]
Die ist leider über 2 Jahre alt. Ich glaube es muss mindestens 1.25.5 sein. Wenn docker über das ppa installiert wird (hier beschrieben https://docs.docker.com/engine/install/ubuntu/) sollte eigentlich eine neuere compose Version dabei sein

**Comment by gbmd** [comment]
Ah peinlich! Wahrscheinlich ein mal apt update dann gibts die neueren versionen... wie gesagt, komplett neues image genutzt.
Danke dir!

**Comment by gbmd** [comment]
Nein, tatsache über apt bekommt ich nur 1.25.0
https://docs.docker.com/compose/install/ hats gelöst.
Danke!
