### ISSUE TITLE
WARNING:charging_profiles:Charging profiles are not yet implemented 

### ISSUE THREAD

**Issue by dewoert** [tillsteinbach/VWsFriend#158]
Don't know when this started, but getting following errors in logging:
`2022-01-29T13:28:25+0000:WARNING:charging_profiles:Charging profiles are not yet implemented {'id': 2, 'name': 'Shell Recharge', 'maxChargingCurrent': 'max', 'minSOC_pct': 0, 'targetSOC_pct': 80, 'options': {'autoUnlockPlugWhenCharged': 'permanent'}, 'preferredChargingTimes': [{'id': 5, 'enabled': False, 'startTime': '21:00', 'endTime': '05:00'}, {'id': 6, 'enabled': False, 'startTime': '21:00', 'endTime': '05:00'}, {'id': 7, 'enabled': False, 'startTime': '21:00', 'endTime': '05:00'}, {'id': 8, 'enabled': False, 'startTime': '21:00', 'endTime': '05:00'}], 'timers': [{'id': 4, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '06:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': False, 'sundays': False}}}, {'id': 5, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '08:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 6, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '06:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
`

**Comment by tillsteinbach** [comment]
Oh this is nice! Finally I have some data how the profiles look like. Will implement the necessary changes in the next days!

**Comment by dewoert** [comment]
I'm using 2 profiles.
This is the one with id : 1, I didn't look yet for differences.
`2022-01-29T13:33:25+0000:WARNING:charging_profiles:Charging profiles are not yet implemented {'id': 1, 'name': 'Thuis', 'maxChargingCurrent': 'max', 'minSOC_pct': 20, 'targetSOC_pct': 80, 'options': {'autoUnlockPlugWhenCharged': 'permanent'}, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTime': '20:05', 'endTime': '05:00'}, {'id': 2, 'enabled': False, 'startTime': '21:00', 'endTime': '05:00'}, {'id': 3, 'enabled': False, 'startTime': '21:00', 'endTime': '05:00'}, {'id': 4, 'enabled': False, 'startTime': '21:00', 'endTime': '05:00'}], 'timers': [{'id': 1, 'enabled': False, 'climatisation': True, 'recurringTimer': {'startTime': '07:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': False, 'sundays': False}}}, {'id': 2, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '08:00', 'recurringOn': {'mondays': False, 'tuesdays': False, 'wednesdays': False, 'thursdays': False, 'fridays': False, 'saturdays': True, 'sundays': True}}}, {'id': 3, 'enabled': False, 'climatisation': False, 'recurringTimer': {'startTime': '06:00', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}
`

**Comment by tillsteinbach** [comment]
Implemented and now in testing for upcoming release
