### ISSUE TITLE
argument -i/--interval: Must be a number not smaller than 180

### ISSUE THREAD

**Issue by gbmd** [tillsteinbach/VWsFriend#159]
docker-compose up liefert:
```
vwsfriend_1   | usage: vwsfriend [-h] [--version] [-u USERNAME] [-p PASSWORD] [--netrc NETRC]
vwsfriend_1   |                  [-i INTERVAL] [--tokenfile TOKENFILE] [--no-token-storage]
vwsfriend_1   |                  [--config-dir CONFIGDIR] [--demo DEMO]
vwsfriend_1   |                  [--privacy {no-locations}] [--with-database]
vwsfriend_1   |                  [--database-url DBURL] [--with-abrp] [--with-homekit] [-v]
vwsfriend_1   |                  [--logging-format LOGGINGFORMAT]
vwsfriend_1   |                  [--logging-date-format LOGGINGDATEFORMAT]
vwsfriend_1   |                  [--hide-repeated-log] [--logging-mail-from LOGGINGMAILFROM]
vwsfriend_1   |                  [--logging-mail-to LOGGINGMAILTO]
vwsfriend_1   |                  [--logging-mail-host LOGGINGMAILHOST]
vwsfriend_1   |                  [--logging-mail-credentials LOGGINGMAILCREDENTIALS LOGGINGMAILCREDENTIALS]
vwsfriend_1   |                  [--logging-mail-subject LOGGINGMAILSUBJECT]
vwsfriend_1   |                  [--logging-mail-notls] [--logging-mail-testmail]
vwsfriend_1   | vwsfriend: error: argument -i/--interval: Must be a number not smaller than 180
vwsfriend_vwsfriend_1 exited with code 2
```

Hi Till, 
seit dem Update heute früh möchte vwsfriend nicht mehr starten. Bin mir nicht sicher, welches Intervall dort übergeben wird, habe die drei health check intervalle im docker-compose.yml auch mal testweise hochgestellt...

VG

ubuntu@vm:~/development/vwsfriend$ docker --version
Docker version 20.10.12, build e91ed57
ubuntu@vm:~/development/vwsfriend$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
ubuntu@vm:~/development/vwsfriend$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by tillsteinbach** [comment]
Wie schaut das .env file aus? (bitte Passwörter auslöschen!)

**Comment by gbmd** [comment]
VWSFRIEND_USERNAME=**
VWSFRIEND_PASSWORD=***
WECONNECT_USER=***
WECONNECT_PASSWORD=***
WECONNECT_PIN=*** # Pin is only necessary for some functions, if your car does not support the>
WECONNECT_INTERVAL=300
DB_USER=***
DB_PASSWORD=***
# If you don't want to use Apple Homekit you can ignore these settings
# The following settings are only used with homekit in macvlan mode
HOMEKIT_INTERFACE=eth0
HOMEKIT_IP=192.168.0.234
HOMEKIT_MASK=192.168.0.0/24
HOMEKIT_GW=192.168.0.1

**Comment by tillsteinbach** [comment]
Just a guess, did you maybe forget `--env-file ./myconfig.env` when starting with docker-compose?

**Comment by gbmd** [comment]
Fixed it, sorry!
