### ISSUE TITLE
Anonymous Auth

### ISSUE THREAD

**Issue by Reinschki** [tillsteinbach/VWsFriend#166]
Hallo Till,
ich würde gerne teile deiner Grafada Grafen etc. in Fhem Tablet UI verwenden, komme aber nicht an die Grafana.ini ran!
(https://www.youtube.com/watch?v=OyJSRLjFHRE)
Das Mappen der Datei über die docker-compose.yml funktioniert nicht.

```
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini 
```
weißt du warum?

Gruß
Reiner

**Comment by tillsteinbach** [comment]
Hmmm das sollte eigentlich so funktionieren wie du das machst.
Du könntest aber stattdessen mal versuchen unter `environment:`
`GF_AUTH_ANONYMOUS_ENABLED=true`
einzufügen

**Comment by tillsteinbach** [comment]
Besteht dieses Problem noch?

**Comment by Reinschki** [comment]
Ist gelöst!
Vielen Dank!
