### ISSUE TITLE
Image missing in grafana & unable to control

### ISSUE THREAD

**Issue by markusstephanides** [tillsteinbach/VWsFriend#17]
Hi there! 

Thank you very much for creating all these weconnect tools!

I just installed VWsFriend on my server running kubernetes and everything went well so far. 

After the installation grafana didn't find the electric car dashboard so I had to manually import it which worked.
But I think there is still something going wrong. I get all the car data but the quick view doesn't work (I also can't find the image that is missing in this repo). And I think using the quick view you should be able to control all the stuff right?

![image](https://user-images.githubusercontent.com/6057570/122210476-faf1ac00-cea5-11eb-987b-7a197cccd5dd.png)

Thanks in advance!

**Comment by tillsteinbach** [comment]
Hey, two points:
- As I wrote under Known Issues: https://github.com/tillsteinbach/VWsFriend#known-issues I cannot publish the nice picture of the ID as I'm not having the license for that. I would need someone to provide such a view of a generic car without a license.
- You cannot control the car from Grafana. If you want to control you can use e.g. my other project: https://github.com/tillsteinbach/WeConnect-cli

If you have further questions let me know!

btw: I'm working on a new version with much more features, but it will take a lot more time.

**Comment by markusstephanides** [comment]
Hi thanks for the explanation and clarification.

Then the readme is a little bit misleading since it says "[...] API visualization and **control** inspired[...] 😀 

Looking forward to the new version!

**Comment by tillsteinbach** [comment]
Ah good point! I now tried to make it more clear that the control part is through the HomeKit App!
