### ISSUE TITLE
Vehicle Parameters for Volkswagen - Internal Server Error

### ISSUE THREAD

**Issue by Reinschki** [tillsteinbach/VWsFriend#183]
Hallo Till,

ich bin aktuell mit dem Setup auf einen andere Maschine umgezogen und bekomme beim speichern der "Vehicle Parameters for Volkswagen" sofort einen "Internal Server Error" und der Container "VWsFriend" geht in unhealthy-Status.

```
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: ""
LINE 1: ...s SET primary_capacity=45, primary_capacity_total='', primar...
                                                             ^
[SQL: UPDATE vehicle_settings SET primary_capacity=%(primary_capacity)s, primary_capacity_total=%(primary_capacity_total)s, primary_wltp_range=%(primary_wltp_range)s, secondary_capacity=%(secondary_capacity)s, secondary_capacity_total=%(secondary_capacity_total)s, secondary_wltp_range=%(secondary_wltp_range)s WHERE vehicle_settings.vehicle_vin = %(vehicle_settings_vehicle_vin)s]
[parameters: {'primary_capacity': 45, 'primary_capacity_total': '', 'primary_wltp_range': 480, 'secondary_capacity': 10, 'secondary_capacity_total': 13, 'secondary_wltp_range': 45, 'vehicle_settings_vehicle_vin': 'WVGZZZ5NZNW?????'}]
(Background on this error at: https://sqlalche.me/e/14/9h9h) (Background on this error at: https://sqlalche.me/e/14/7s2a)
```
Auch der Rückweg funktioniert nicht mehr... Gleiches Verhalten wie geschildert.
Ich blicke  nicht mehr durch!

Hast du einen Idee?
Gruß
Reiner

**Comment by tillsteinbach** [comment]
Hallo Reiner, hast du bei "Total Battery Capacity (gross) in kWh" etwas eingetragen?

**Comment by tillsteinbach** [comment]
Ah, ich glaube ich sehe das problem

**Comment by tillsteinbach** [comment]
Du hast da einen Bug gefunden. Ich versuche bis heute Abend noch eine 0.16.3 zu releasen.

**Comment by Reinschki** [comment]
Hi, 
jetzt kann ich das Dialogfeld abschließen!

Eine Warnung in Grafana ist übriggeblieben:
`Some panels need the tank size of Volkswagen to be set. Please set the size here: [Vehicle Parameters]`

Ich habe alle Felder ausgefüllt!

Besten Dank!

**Comment by tillsteinbach** [comment]
Danke! Den Fehler habe ich auch gefunden! Dann gibt es noch ein update

**Comment by tillsteinbach** [comment]
Warning sollte mit der 0.16.4 auch weg sein.
