### ISSUE TITLE
VWsFriend UI authentication

### ISSUE THREAD

**Issue by Gregoire-M** [tillsteinbach/VWsFriend#184]
Hi,
Since recent update, login/password are prompted when accessing to UI (not grafana).
What are those credentials? How can we configure it?
I can't find this in the doc.

Thanks!

<img width="982" alt="image" src="https://user-images.githubusercontent.com/475728/157009373-a3f9a5e5-fb51-42f3-a9d5-490aa0ccac2c.png">

**Comment by tillsteinbach** [comment]
You need to update also the docker-compose.yml file this time. If you do so the user/password is the same like in grafana

**Comment by Gregoire-M** [comment]
Okay, it works now, thank you!
