### ISSUE TITLE
No location recorded

### ISSUE THREAD

**Issue by risdevs** [tillsteinbach/VWsFriend#189]
I installed VWsFriend a couple of days ago, with the default config (only pw was changed)
Trips and charging events are logged, but no location data is available for either.

Can you give me some pointers for trying to debug it?

**Comment by tillsteinbach** [comment]
If it is a car of the MEB family (ID.3/4) you can currently not record locations. You will need to wait until your car got the firmware update 3.0

is that the case for you?

**Comment by risdevs** [comment]
oh, I didn't knew that.
Yes, sorry, it's an ID.4

Another reason to look forward to 3.0 update 🙃 

Thanks!

**Comment by risdevs** [comment]
I have (finally!) installed 3.0, and enabled the We Connect services (and if I open the WeConnect app, it shows the last parking position).
But the location is still not being tracked in VWsFriend.

Can you give me some pointers for trying to debug it?

**Comment by tillsteinbach** [comment]
Did you restart VWsFriend after the 3.0 update?

**Comment by risdevs** [comment]
😳 
It worked after restarting 😄 

Thanks!
