### ISSUE TITLE
Publish values to MQTT in parallel

### ISSUE THREAD

**Issue by tmakowka** [tillsteinbach/VWsFriend#219]
Hi @tillsteinbach 

as mentioned in the Going Electric Forum already, it would be great to have the opportunity to publish the fetched values to a central MQTT service in parallel, just as WeConnect-mqtt is doing it already. This would give users the possibility to use the data in other solutions, in my example i'd like to integrate the data into Home Assistant (my Smarthome solution), without having to gather the data twice from the Volkswagen API, which would result in 2x service calls on VW's end.

It would be great to see this implemented in the future.

Apart from that, this looks like a super-cool solution, i just installed it and i'm eager to drive my ID.4 for the next time for seeing the results in the dashboard ;)

Thanks Torben

**Comment by tmakowka** [comment]
Wohoo, that's great news! Thanks for implementing, looking forward to the next release!

**Comment by tillsteinbach** [comment]
Now supported with 0.20.0

**Comment by tmakowka** [comment]
Hi @tillsteinbach, thanks a lot! I updated to the latest version, but i can't figure out how to configure this feature in VWsFriend. The documentation leads to the weconnect-mqtt documentation, which states that the commandline needs to be adjusted. But how can this be achieved in the containerized approach VWsFriend is using?

As far as i understand the setup, probably additional ENV variables need to be defined? If so, is there any documentation on them?

Thanks Torben

**Comment by tillsteinbach** [comment]
Just use the same command line options as in WeConnect-mqtt and add those to ADDITIONAL_PARAMETERS

**Comment by thgau** [comment]
> Just use the same command line options as in WeConnect-mqtt and add those to ADDITIONAL_PARAMETERS

Can you add this information to your README.md? I was also searching where to put this parameters.

And thanks for the MQTT support.

**Comment by tillsteinbach** [comment]
Done
