### ISSUE TITLE
Grafana Container doesn´t start

### ISSUE THREAD

**Issue by gnu300** [tillsteinbach/VWsFriend#224]
Hi,

since, i guess, today, the grafana container does not start anymore, to be more precise the container is stuck in the "starting" state:

```
$ docker ps -a | grep grafana
015833e67ae1   tillsteinbach/vwsfriend-grafana:latest   "/run.sh"                6 minutes ago   Up 3 seconds (health: starting)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   vwsfriend_grafana_1
```

The logs state that there is an error with the plugin repo of marcusolsson-json-datasource:

```
$ docker logs vwsfriend_grafana_1
Error: ✗ Get "https://grafana.com/api/plugins/repo/marcusolsson-json-datasource": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Error: ✗ Get "https://grafana.com/api/plugins/repo/marcusolsson-json-datasource": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Error: ✗ Get "https://grafana.com/api/plugins/repo/marcusolsson-json-datasource": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

BR,
Gernot

**Comment by tillsteinbach** [comment]
Hmm, maybe a problem with your internet connection? It looks like a problem while downloading the plugins.

**Comment by gnu300** [comment]
Sorry, yes, this was my fault. Since the VM with the container has a public IP and is directly exposed with no firewall, since I still wanted to restrict the access to it I added the following iptables rule:
```
iptables -I DOCKER-USER -i eth0 ! -s <home-ip> -j DROP
```
and this leads to the behaviour that the return DNS packets are dropped since there is no corresponding "ESTABLISHED, RELATED" rule, the correct iptables rules for my use-case are:
```
iptables -I DOCKER-USER -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -I DOCKER-USER -i eth0 ! -s <home-ip> -j DROP
```
