### ISSUE TITLE
Unknown Username or wrong password

### ISSUE THREAD

**Issue by Flo-63** [tillsteinbach/VWsFriend#229]
Hi,
First, thanks for the great tool! 
Grafana Part is up and running at my side, but for whatsoever reason, I'm no longer able to log into the vwsfriend part of the environment. I use the username/password combination defined in myconfig.env but receive the error message apove... is there any chance to reset the password?

Thx

Florian

**Comment by tillsteinbach** [comment]
I guess you are speaking about `VWSFRIEND_USERNAME` and `VWSFRIEND_PASSWORD`. If you can log into grafana initial setup of the passwords should be fine I think. Is that a new installation or an update of an older installation? In case it was an update please also update the docker-compose.yml file.

**Comment by tillsteinbach** [comment]
just replace the old .yml with the new one

**Comment by Flo-63** [comment]
Thx, Rebuilding the entire environment did the trick!

Best regards!
