### ISSUE TITLE
Enhancement charging statistics > Charging speed by SoC

### ISSUE THREAD

**Issue by MattiJarvinen** [tillsteinbach/VWsFriend#245]
It would be nice to have AC / DC separation here.

With a BEV AC is likely constant or reduced by user settings and it's useless to follow.
DC charge graph is more interesting especially if one could compare it summer to winter ( since preconditioning isn't available for ID cars.).

**Comment by thgau** [comment]
For me the AC is varying very much as it is controlled by a PV (photo voltaic).

**Comment by tillsteinbach** [comment]
I already have thrown AC out for the next release. It is just not meaningful because it is either constant or not depending on the SoC.
