### ISSUE TITLE
Grafana doesn't get any data (synology/docker)

### ISSUE THREAD

**Issue by escuco** [tillsteinbach/VWsFriend#246]
I've installed the latest docker container vwsfriend and vwsfriend-grafana on my Synology NAS and configured vwsfriend like described in the wiki: [https://github.com/tillsteinbach/VWsFriend/wiki/Install#install-on-synology-docker-native-synology-ui-no-docker-compose](https://github.com/tillsteinbach/VWsFriend/wiki/Install#install-on-synology-docker-native-synology-ui-no-docker-compose)

I can now login to vwsfriend on my NAS on ip_adress:4000 and I get the Vehicle Status for my ID.3 without any problems.

After that I configured also vwsfriend-grafana, but after log in on ip_adress:3000 I get only some blank "no data" controls and a warning "You have to set the URL for the VWsFriend user interface correctly: Go to the user interface on port 4000 and select "Database" > ”Connection Settings"".

Back on the user interface from vwsfriend I can not find any Database settings. Only the status page, where I can pick my car and view the informations and status from the car.

Back on the Synology docker settings for vwsfriend-grafana I've checked the VWSFRIEND_HOSTNAME setting and it seems ok:

![Screenshot_20220606_173252](https://user-images.githubusercontent.com/1647405/172194389-9f383227-9906-4d6c-8d3f-aa23834cc283.png)

Is there anything I have to configure for Grafana?

Thank you!

**Comment by tillsteinbach** [comment]
Did you also Setup the postgres container?

**Comment by escuco** [comment]
I installed and set up the postgres container and configured the hosts IP in the docker settings for the grafana docker (DB_HOSTNAME). But for now, without any further access.

I've taken some screenshots from the container settings - maybe this helps.

**Postgres Container Settings**
![Screenshot_Postgres](https://user-images.githubusercontent.com/1647405/172330370-342fcc66-6b0f-4002-88de-2e06a9e0b0c0.png)


**VWsFriends Container Settings**
![Screenshot_VWsFriends](https://user-images.githubusercontent.com/1647405/172330433-d579f628-6b5d-4133-8eb4-6525a7ad8336.png)


**VWsFriends-Grafana Container Settings**
![Screenshot_VWsFriends-Grafana01](https://user-images.githubusercontent.com/1647405/172330537-6ad5bca7-6ab5-46bf-a3e7-2d94313f9401.png)

![Screenshot_VWsFriends-Grafana02](https://user-images.githubusercontent.com/1647405/172330544-542840b1-fb95-405b-914c-3e7a88fcf9c3.png)

![Screenshot_VWsFriends-Grafana03](https://user-images.githubusercontent.com/1647405/172330561-cefb7e83-4565-4faf-8bd7-df54c80228d5.png)


**Web UI** 
![Screenshot_web_ui_01](https://user-images.githubusercontent.com/1647405/172330634-d57f1648-7ffe-44aa-99d4-52ddd9946696.png)


**WEB UI after clicking the two gears**
![Screenshot_web_ui_02](https://user-images.githubusercontent.com/1647405/172330739-bd1558db-7fe8-4ca3-b919-75dd4c910f5c.png)


**Web UI after clicking on my car**
![Screenshot_web_ui_03](https://user-images.githubusercontent.com/1647405/172330856-ba041fbe-90d9-4864-b35e-9768d859288c.png)


**Web UI Grafana with errors**
![Screenshot_Grafana](https://user-images.githubusercontent.com/1647405/172331235-6395c9c6-3d5c-44ee-bb95-2f6b59abbcea.png)

**Comment by tillsteinbach** [comment]
Do you have the connection settings environment variable:
`DATABASE_URL=postgresql://${DB_USER-admin}:${DB_PASSWORD-secret}@${DB_HOSTNAME-postgresdbbackend}:${DB_PORT-5432}/${DB_NAME-vwsfriend}`
and
`—with-database` In the ADDITIONAL_PARAMETERS?

**Comment by escuco** [comment]
After adding the ADDITIONAL_PARAMETER and the string for DATABASE_URL:

![Screenshot_20220608_112614](https://user-images.githubusercontent.com/1647405/172583883-e83bee5c-0bbd-4c4e-a2dd-a8d834ef6a1d.png)

the VWsFriends container doesn't start and the log throws this output:

![Screenshot_20220608_112751](https://user-images.githubusercontent.com/1647405/172583985-1b79c029-8c93-41d1-b5b6-481b886d4d0d.png)

I think it has to do with Synologys own Docker implementation (and editing) of the .env file with the Disk Station Manager. 

Maybe I'm now going to cancel the installation with Synologys DSM and try it with docker compose on the console.

**Comment by tillsteinbach** [comment]
Ah yes I think the variables are only substituted in docker compose. So you have to replace the variables the real values. e.g. `${DB_USER-admin} ` with the database password you configured in postgres.

**Comment by tillsteinbach** [comment]
The error looks like there is no connection at all possible to the database. It is sometimes a bit tricky to allow connections between the containers. Maybe you have to configure something in the UI for it to work?

Regarding the database. The database should exist if you put the Variable `POSTGRES_DB=vwsfriend` to the postgres container. It then creates it when starting the first time.

**Comment by escuco** [comment]
> One last question: What is the difference between "Usable battery capacity (net)" and "Total battery capacity (gross)" in the vehicle parameters form?

Ah, I found it by myself.

**Comment by tillsteinbach** [comment]
Great that it works now!
If you would write a small manual for the DSM setup I would be very happy adding it to the wiki for other users.

**Comment by escuco** [comment]
I'll write a documentation for the installation with DSM **and** ssh (which also works fine with synology), when I find some time.

**Comment by piridium** [comment]
@escuco Did you find time to write the documentation? I'm stuck at the same problem.
