### ISSUE TITLE
can't edit charging session

### ISSUE THREAD

**Issue by upelectric** [tillsteinbach/VWsFriend#253]
Hi, I got vwsfriend to run but I can't edit a charging session to add costs, real charged kWh, charges, ...
If I press "Save changes" I can see that the (unchanged) charging end date has a wring format.

![grafik](https://user-images.githubusercontent.com/107312763/173192173-7ddb6f2f-62a0-4bd8-9929-93860523905b.png)

There are no error messages but if I open the seession again my changes are lost.

**Comment by tillsteinbach** [comment]
Can you try if you can set the time if you put :01 for the seconds? I have a feeling that the browser might suppress the seconds if zero.

**Comment by upelectric** [comment]
Yes, that was the problem. Thanks.

**Comment by tillsteinbach** [comment]
Ok, I will try to fix that as soon as I find a solution

**Comment by tillsteinbach** [comment]
Issue found, will be fixed in the next release.

**Comment by tillsteinbach** [comment]
Fixed in 0.18.2
