### ISSUE TITLE
WARNING: An unsupported externalPower, An unsupported ledColor

### ISSUE THREAD

**Issue by thgau** [tillsteinbach/VWsFriend#259]
I have these entries in my log:
vwsfriend_1   | 2022-06-23T07:59:24+0000:WARNING:addressable:/vehicles/WVGZZZE2..../domains/charging/plugStatus/externalPower: An unsupported externalPower: active was provided, known values are [ready, unavailable, unknown external power] please report this as a bug
vwsfriend_1   | 2022-06-23T07:59:24+0000:WARNING:addressable:/vehicles/WVGZZZE2.../domains/charging/plugStatus/ledColor: An unsupported ledColor: green was provided, known values are [none, unknown plug led color] please report this as a bug

not sure since when this is there. I just noticed it after a restart.

My car is an ID.4

**Comment by tillsteinbach** [comment]
Hey @thgau, this should be gone after updating to the latest update [0.19.0](https://github.com/tillsteinbach/VWsFriend/releases/tag/v0.19.0)

**Comment by tillsteinbach** [comment]
Ah, sorry! I just saw that you got new values. Will push a 0.19.1 to fix that ASAP.

**Comment by tillsteinbach** [comment]
The new values are now available after update to 0.19.1
If you could do me a favour and monitor the next days for the LED-Colors? I added red and green, but probably there are more possibilities.

**Comment by thgau** [comment]
Until now no new colors appeared. The car manual mentions a white color at the start of a DC charging session.
