### ISSUE TITLE
Add charging session datetime

### ISSUE THREAD

**Issue by MattiJarvinen** [tillsteinbach/VWsFriend#266]
Something funny with the datetime payloads.

Microsoft Edge
Version 103.0.1264.37 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/12794435/175822329-78a33383-be44-4e24-b108-b49229c0488e.png)
![image](https://user-images.githubusercontent.com/12794435/175822257-638cd6c4-a08d-4f43-b781-7b0b3297fe5a.png)

Google Chrome
Version 102.0.5005.115 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/12794435/175822442-8ab23a1c-855e-4df3-b618-d9cea2d863b4.png)
![image](https://user-images.githubusercontent.com/12794435/175822466-726a2f23-23e0-41d0-93fe-836523542106.png)

WTForms datetime separator might be the origin here?
https://github.com/wtforms/wtforms/issues/720

**Comment by tillsteinbach** [comment]
Is this also on 0.19.0? This should have been fixed recently.

**Comment by tillsteinbach** [comment]
See here https://github.com/tillsteinbach/VWsFriend/issues/253

**Comment by MattiJarvinen** [comment]
Yeah, for some reason my version was 0.16.6. It's fixed.
