### ISSUE TITLE
vwsfriend stopped recording after error

### ISSUE THREAD

**Issue by thgau** [tillsteinbach/VWsFriend#268]
I got this error around the time when AC loading started this morning. Since then no more data was recorded but the container did also not stop, Had to restart the container manually. 
vwsfriend_1   | 2022-06-28T04:54:58+0000:INFO:vwsfriend_base:Updating data from WeConnect
vwsfriend_1   | Traceback (most recent call last):
vwsfriend_1   |   File "/opt/venv/bin/vwsfriend", line 8, in <module>
vwsfriend_1   |     sys.exit(main())
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/vwsfriend_base.py", line 282, in main
vwsfriend_1   |     weConnect.update(updateCapabilities=True, updatePictures=True, force=True)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/weconnect/weconnect.py", line 177, in update
vwsfriend_1   |     self.updateComplete()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete
vwsfriend_1   |     child.updateComplete()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete
vwsfriend_1   |     child.updateComplete()
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 518, in updateComplete
vwsfriend_1   |     child.updateComplete()
vwsfriend_1   |   [Previous line repeated 3 more times]
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/weconnect/addressable.py", line 96, in updateComplete
vwsfriend_1   |     observer(element=self, flags=self.onCompleteNotifyFlags)
vwsfriend_1   |   File "/opt/venv/lib/python3.9/site-packages/vwsfriend/agents/charge_agent.py", line 258, in __onPlugLockStateChange
vwsfriend_1   |     and self.chargingSession.ended > (plugStatus.carCapturedTimestamp.value - timedelta(hours=24)):
vwsfriend_1   | TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'

**Comment by tillsteinbach** [comment]
I think I have found the problem. Will prepare a 0.19.2 bugfix release

**Comment by tillsteinbach** [comment]
Ok, 0.19.2 is out. I hope this will fix the problem.
