### ISSUE TITLE
bug: No values for charging session with nothing charged (pv überschuss)

### ISSUE THREAD

**Issue by daniel-w00** [tillsteinbach/VWsFriend#282]
If you charge with PV, it can happen that you plug the charger in but nothing is charged because the pv energy is not enough. (The car has than often an error the whole charging time)
Currently a charging session with no values is than stored. The session should have 0kwh, start and end soc, etc... 

![image](https://user-images.githubusercontent.com/81196484/180326254-841266a1-3115-49df-9e5f-e42b320bf77e.png)

![image](https://user-images.githubusercontent.com/81196484/180262333-d7542fd1-6371-4b0b-b974-5dbcc01ce1e7.png)

**Comment by tillsteinbach** [comment]
This is on purpose. It makes it much easier to see sessions where the charging was never started. %Start is the SoC when the charging was started, not when the car was connected.

**Comment by daniel-w00** [comment]
Okay, thanks.
And is it on purpose if you want to delete this session, you have to at first fill out the start date field with some numbers until you can delete the session?
![image](https://user-images.githubusercontent.com/81196484/180650616-9750000d-7ac3-4343-8e93-1183c36c2d81.png)

**Comment by tillsteinbach** [comment]
No :) good catch! That is a bug.

**Comment by tillsteinbach** [comment]
Fixed in 0.20.0
