### ISSUE TITLE
Use "Tooltip mode = All" to improve readability of data when lines are close together

### ISSUE THREAD

**Issue by simboel** [tillsteinbach/VWsFriend#283]
Currently the panels in the dashboard use "Tooltip mode = Single". This makes it hard to get data for all multiple series that are visually close together.

**Problem visualized**

Please note, that event though my mouse is always between both lines, just one series will be shown in the tooltip.

![image](https://user-images.githubusercontent.com/5895949/180638391-b38d790f-63d0-4926-9b4b-a514ed6e2787.png)
![image](https://user-images.githubusercontent.com/5895949/180638229-766d08af-6c8a-4a1d-a421-e47148b37ba2.png)

**Possible solution**

You can set the "Tooltip mode" to all for panels in the panel options.

![image](https://user-images.githubusercontent.com/5895949/180638360-aa04ffef-f993-45a0-8fc1-a3d4dbcd21b5.png)

This will then show the data for all lines:
![image](https://user-images.githubusercontent.com/5895949/180638379-baf15ca0-f843-4a24-bafa-59c05f3a75a0.png)

**Comment by tillsteinbach** [comment]
Good proposal. Will change that with the next release!

**Comment by tillsteinbach** [comment]
Released with 0.20.0
