### ISSUE TITLE
vertical lines in car overwiew dashboard

### ISSUE THREAD

**Issue by daniel-w00** [tillsteinbach/VWsFriend#289]
Are these vertical lines neccessary or can they be deleted? Looks not so nice with a big time range
![image](https://user-images.githubusercontent.com/81196484/181127086-0ec4a794-bcd2-44d1-9508-91d824a8b295.png)

**Comment by tillsteinbach** [comment]
You can switch off the „Online“ slider at the top. Then the lines are gone.
Unfortunately there is no way to make the lines conditional based on the time-range.

**Comment by daniel-w00** [comment]
Ah, thanks! Didn't found that
