### ISSUE TITLE
[Docker + Apache] Grafana can't display car badge

### ISSUE THREAD

**Issue by Gregoire-M** [tillsteinbach/VWsFriend#293]
Hi,

First of all, my setup is a bit complex, so I understand if is not supported.

I have a dedicated server, with several websites, handled by Apache virtual hosts. I've added VWsFriend using docker-compose. I access Grafana and car settings by adding those Apache virtual hosts (basically, I tell Apache to redirect trafic to given port according to the hostname):

```
<VirtualHost *:443>
    ServerName mycar.mywebsite.com
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
    ProxyPreserveHost On
</VirtualHost>

<VirtualHost *:443>
    ServerName mycaradmin.mywebsite.com
    ProxyPass / http://127.0.0.1:4000/
    ProxyPassReverse / http://127.0.0.1:4000/
    ProxyPreserveHost On
</VirtualHost>
```

It works fine, except that links from Grafana to VWsFriend aren't right. So the car badge can't be displayed for example:

<img width="577" alt="image" src="https://user-images.githubusercontent.com/475728/181802777-004f8bf0-ff1c-438a-ae2b-d1f6cdc2bf4d.png">

The image src is something like:
```
http://mymainwebsite:4000/status/vehicles/WVWXXXXX-status_or_car-badge.png
```
Instead of:
```
https://mycaradmin.mywebsite.com/status/vehicles/WVWXXXXX-status_or_car-badge.png
```

Is there something I can do with docker env vars to fix this?

Thanks!

**Comment by tillsteinbach** [comment]
Ok, first a disclaimer: "Please be super careful when you open VWsFriend to the public."

If I understand your setup right you need to go here:
`https://mycaradmin.mywebsite.com/database/settings/edit`
and edit `URL where the VWsFriend installation is reachable` from `http://mymainwebsite:4000` to `https://mycaradmin.mywebsite.com`

**Comment by Gregoire-M** [comment]
When you say
> Please be super careful when you open VWsFriend to the public.
You're talking about the `vwsfriend` container only, right? Or exposing the grafana container is risky too?

Currently, I only enable the VWsFriend VHost when I need to update settings.
So I've tested the database setting, and it works! Thanks :)

But in the end, I think I won't let the VWsFriend VHost enabled just to have an image of my car... Would it be possible to host the image in Grafana ?

**Comment by tillsteinbach** [comment]
I think you should be fine with enabling the vwsfriend container also as you have https and password protection. But this is a one-man-show open source project. So I cannot guarantee that there is not a way into the system that could get e.g. your password stolen. Therefore the disclaimer.

Unfortunately there is no way to host the images in grafana. The only other way I can imagine is to base64 encode them and provide them through json to grafana.

**Comment by Gregoire-M** [comment]
Thank you for your answers

**Comment by tillsteinbach** [comment]
Next release will be able to show the images with grafana proxying the data. So grafana will fetch the images through the backend and serve them to the browser.

**Comment by Gregoire-M** [comment]
Awesome! Thank you 😊
