### ISSUE TITLE
charging stataistics dashbaord - tooltip

### ISSUE THREAD

**Issue by daniel-w00** [tillsteinbach/VWsFriend#313]
Is it inevitable that the the power distribution plot in the charging statistics dashboard displays -5.0 to 5.0 kW instead 0 kW to 5 kW?

And I don't think the exact value in the first row of the tooltip is necessary. Maybe just:
    0 kW to 5 kW: 
    40.2 % of charging time
?

The plot looks probably nice if you charge more with DC than I do. Maybe it's an idea to have a smaller bucket size until 11 kw or to separate AC and DC. But it's maybe difficult to have something here that fits everyone with different charging behavior.

![grafik](https://user-images.githubusercontent.com/81196484/184753736-6df51485-cfd0-4d14-9599-770c26631acb.png)

**Comment by tillsteinbach** [comment]
Yes, it is super difficult to make it right for everyone. But I can try out smaller buckets for 11kW and below. Maybe 1 or 2 kw?

**Comment by tillsteinbach** [comment]
![image](https://user-images.githubusercontent.com/3825852/184822594-2a7f274d-b56a-466d-8ee0-a4e9d6aac04b.png)

**Comment by tillsteinbach** [comment]
For the first line in the tooltip I have not found a way yet to remove it.

**Comment by daniel-w00** [comment]
Great. 1 kW bucket size would be too small, I think. I guess maybe even 3 kw would be okay. Than you have 4 buckets till 11kw.

By the way, means the percentage value, percent of time or percent of amount kWh charged. Maybe this could be added in the info.

**Comment by tillsteinbach** [comment]
Changed in 0.21.0
