### ISSUE TITLE
charging with 11kw is showing as 10.5kW

### ISSUE THREAD

**Issue by daniel-w00** [tillsteinbach/VWsFriend#316]
If the WeConnect ID App shows charging with 11kW (and my wallbox too), vws friend olny shows 10.5 kW.
Is this a bug or has this a reason?

**Comment by tillsteinbach** [comment]
This is what is coming from the API. I don't know if the App is maybe rounding up to 11kWh.

**Comment by daniel-w00** [comment]
okay, thanks. Interesting...
