### ISSUE TITLE
values for charging sessions are missing although charging started

### ISSUE THREAD

**Issue by daniel-w00** [tillsteinbach/VWsFriend#317]
charging sessions:

![grafik](https://user-images.githubusercontent.com/81196484/186419017-bf0bde6e-d1ac-480e-bbd5-70e737389608.png)

first charge started at 97% to 99%
![grafik](https://user-images.githubusercontent.com/81196484/186170262-11a3f0a0-7d19-428f-b21c-999911a6d96d.png)

trip started:
![grafik](https://user-images.githubusercontent.com/81196484/186170402-2bbac542-6118-4cd0-8e07-fd57b526131c.png)

trip ended and charger connected and charging started from 98% to 100%:
![grafik](https://user-images.githubusercontent.com/81196484/186170334-56b326cb-d667-4bf8-9e88-d836148f5f02.png)

**Comment by tillsteinbach** [comment]
hmmm that is super strange. It did not detect that the plug was disconnected at 11:41

The PV overhead charging is quite a chalange to handle correctly

**Comment by daniel-w00** [comment]
Okay no problem, but I thought i better create an issue.

The second charging is not a charging with pv. That was normal charging with reduced AC power.
