### ISSUE TITLE
Show only Battery Level diagram for BEVs

### ISSUE THREAD

**Issue by amenychtas** [tillsteinbach/VWsFriend#322]
For BEVs, the diagrams `Battery Level` and `Levels & Range` depict exactly the same information. It would be nice if only one is presented in the default dashboard in case of BEV.

![image](https://user-images.githubusercontent.com/3939897/188470885-77f46aca-d331-4e66-a761-e321f5260f0d.png)

**Comment by tillsteinbach** [comment]
Unfortunately it is currently not possible to dynamically hide panels. Once this is available in grafana I will make the Range panel only visible for hybrid cars.
