### ISSUE TITLE
role "root" does not exist

### ISSUE THREAD

**Issue by xerion3800** [tillsteinbach/VWsFriend#35]
Wenn ich den Container mit "docker-compose --env-file ./myconfig.env up" starte bekomme laufend folgenden Fehlermeldung:

grafana_1     | t=2021-09-07T12:03:02+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=127.0.0.1 time_ms=0 size=29 referer=
postgresdb_1  | 2021-09-07 12:03:09.954 UTC [347] FATAL:  role "root" does not exist
postgresdb_1  | 2021-09-07 12:03:20.221 UTC [355] FATAL:  role "root" does not exist
postgresdb_1  | 2021-09-07 12:03:30.454 UTC [364] FATAL:  role "root" does not exist
postgresdb_1  | 2021-09-07 12:03:40.679 UTC [373] FATAL:  role "root" does not exist

**Comment by tillsteinbach** [comment]
oh ja, das habe ich auch. Sollte trotzdem funktionieren. Ich schau mal wie das weg geht...

**Comment by tillsteinbach** [comment]
Ahhh, ich glaube das kommt vom healthcheck. Mal sehen wie ich das fixen kann

**Comment by tillsteinbach** [comment]
Vermutung war correct. Mit dem docker-compose file was jetzt da ist ist der Fehler weg
