### ISSUE TITLE
Trips stop saving until restart

### ISSUE THREAD

**Issue by Mavyre** [tillsteinbach/VWsFriend#355]
I just noticed that the trips are stopping being monitored and saved into the database util I restart VWsFriend (either a restart of the docker container, or using /restart route). No errors in the logs - or didn't found the correct error log file.

I've got a VW Golf GTE from 2020, which only sends data to the app during state changes or while charging.

**Comment by ramonetdev** [comment]
It's almost what's happening to me but in my case, the charges aren't registered either. I have an e-golf from 2019.

**Comment by tillsteinbach** [comment]
I‘m trying to find a solution.

**Comment by amenychtas** [comment]
I confirm this with my ID.3 SW v2.4. A single trip is recorded after restarting the container and then trip recording stops.
Charging recording seems to be working properly.

**Comment by MattiJarvinen** [comment]
Public release of 3.0 OTA could be still a year away. 

VW has only stated it will do this one 1000 opt-in OTA and there hasn't been any posts about them even resuming the release in Germany.

A few of those 1000 have been bricked in the update process and had to be towed away spending 1 week at the shop to receive some parts so I'd expect couple more months for the fixes, then another 1000 - rinse and repeat.

**Comment by tillsteinbach** [comment]
There is a hope that the trip recording for pre 3.0 is fixed now. I'm currently in testing.

**Comment by tillsteinbach** [comment]
Fixed in 0.23.1

**Comment by bendavidson** [comment]
Can confirm, trips now working with an ID.4 running software version 2.4
(hadn't recorded any trips since I had the upgrade done at the dealer a
couple of months ago)
