### ISSUE TITLE
Range Status warning

### ISSUE THREAD

**Issue by upelectric** [tillsteinbach/VWsFriend#364]
I get warnings about the Range_status.

WARNING:range_status:/vehicles/WVWZZZ3CZNEXXXXXX/domains/fuelStatus/rangeStatus/primaryEngine: Unknown attribute currentFuelLevel_pct with value 33

Vehicle is a Passat GTE.

**Comment by tillsteinbach** [comment]
Thanks for reporting! This is known and will be fixed with the next release.

**Comment by tillsteinbach** [comment]
Should be fixed in 0.23.0
