### ISSUE TITLE
Some trips are not recorded

### ISSUE THREAD

**Issue by aimsire** [tillsteinbach/VWsFriend#365]
Hey there,

as already mentioned in issue #363, some trips are not being recorded for me, without any error messages displayed.
Example from today: I drove from home (A) to location B, from B to location C, from C to location D and from D back to A (home). Only trips recorded are: B -> C, C -> D, D -> A. Car logs as online, but gauging from the timestamp only after already arriving on location B. It is a short trip, a little bit over 1km - but trip from D -> A was even shorter and was recorded correctly.

Is it possible that this is related to the frequency VWsfriend is updating? I left it at default.

**Comment by tillsteinbach** [comment]
Yes that is possible. How long is your short trip?

**Comment by aimsire** [comment]
Depends on traffic of course, but I think I could make it under 3 minutes and therefore being in the dark in the worst case? I've set it down to 120 seconds now, lower it didn't let me and will test again.

**Comment by aimsire** [comment]
By increasing the update frequency, the problem did not occur again. Are there any plans to make it possible to set it below 120s? It would be great to adjust it via home automation depending on whether someone is using the car. 
But I just wanted to say that I love this project and thank you so much for creating it!
