### ISSUE TITLE
vwsfriend als Dienst auführen

### ISSUE THREAD

**Issue by unknownuser26** [tillsteinbach/VWsFriend#372]
Hallo,
erstmal ein großes Dankeschön an den/die Entwickler @tillsteinbach !

Ich habe vwsfriend ohne Docker installiert und das läuft soweit auch sehr gut, aber ich möchte gerne das vwsfriend als Dienst asugeführt wird und das funtkioniert leider nicht.
Hat jemand ein Beispiel oder einen Tipp?

Die Path Variablen habe ich bereits angepasst.

**Comment by cmantsch** [comment]
Ein paar mehr Informationen wären hilfreich, also wie sieht die aktuelle Konfiguration aus, welche Umgebung wird verwendet (Betriebssystem) und was wurde schon versucht. Sonst ist das alles nur ein stochern im Dunkeln ;)
