### ISSUE TITLE
Location and Odometer after update to 3.0

### ISSUE THREAD

**Issue by kmarcin-22** [tillsteinbach/VWsFriend#380]
Hi
My ID.3 finished 3.0 update yesterday. In Vwsfriend I began seeing parking location, and open windows. Unfortunately odometer, charging location and journey location data are missing. 
Odometer dashboard  shows - no data from car
I already restarted docker, but no change. Is there anything else I can check in Vwsfriend or is it the car software?

**Comment by tillsteinbach** [comment]
Did you drive after the docker restart?

**Comment by kmarcin-22** [comment]
Yes, multiple times

**Comment by tillsteinbach** [comment]
Hmm fortunately I should have 3.0 also in the next days and can debug myself

**Comment by kmarcin-22** [comment]
Keeping my fingers crossed 
I checked vehicle capabilities and looks like some parts are disabled. I don’t know if it should be like this

![C5FCD86C-A23A-4A58-96C0-0C628898F754](https://user-images.githubusercontent.com/121283658/209427560-62bf56be-948d-4215-aedc-d9ec9748ac75.jpeg)

**Comment by tillsteinbach** [comment]
Maybe privacy settings?

**Comment by kmarcin-22** [comment]
In car I allowed everything:/

**Comment by kmarcin-22** [comment]
Hmm
Odometer just appeared. Maybe there is some backend update connected with car update and it was delayed?
