### ISSUE TITLE
Grafana password?

### ISSUE THREAD

**Issue by kmarcin-22** [tillsteinbach/VWsFriend#400]
Hi
Today my grafana dashboard stopped accepting my login credentials and shows login screen. 
I suspect it has something to do with those messages about config overridden showing up in console, has anything been changed in container?

logger=settings t=2023-01-17T19:42:18.221628336Z level=info msg="Starting Grafana" version=9.2.6 commit=8ba6f0f1a8 branch=HEAD compiled=2022-11-22T09:10:38Z
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.22226319Z level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.22237956Z level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.222473521Z level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.222737592Z level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.222847773Z level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.222963234Z level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223064104Z level=info msg="Config overridden from command line" arg="default.log.mode=console"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223158545Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223235535Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223304136Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223374276Z level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223452597Z level=info msg="Config overridden from Environment variable" var="GF_SERVER_HTTP_PORT=40054"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223532667Z level=info msg="Config overridden from Environment variable" var="GF_SERVER_ENABLE_GZIP=true"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223664398Z level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_USER=admin"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223740668Z level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_PASSWORD=*********"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223810049Z level=info msg="Config overridden from Environment variable" var="GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana-static/dashboards/vwsfriend/VWsFriend/overview.json"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.223909809Z level=info msg="Config overridden from Environment variable" var="GF_USERS_ALLOW_SIGN_UP=false"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.22400151Z level=info msg="Config overridden from Environment variable" var="GF_ALERTING_ENABLED=false"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.22406945Z level=info msg="Config overridden from Environment variable" var="GF_EXPLORE_ENABLED=false"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.224142471Z level=info msg="Config overridden from Environment variable" var="GF_METRICS_ENABLED=false"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.224244911Z level=info msg="Config overridden from Environment variable" var="GF_PLUGINS_ENABLE_ALPHA=true"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.224344612Z level=info msg="Config overridden from Environment variable" var="GF_PLUGINS_PLUGIN_ADMIN_ENABLED=false"
famkot-grafana-1     | logger=settings t=2023-01-17T19:42:18.224417892Z level=info msg="Config overridden from Environment variable" var="GF_EXPRESSIONS_ENABLED=false"

**Comment by kmarcin-22** [comment]
I managed to get it back to work afer deleting all volumes. Lost all data though:/

**Comment by tillsteinbach** [comment]
Did you change your password in Grafana?
Before you delete a volume, always do a backup of the data in the UI before. You can restore the backup afterwards.

**Comment by kmarcin-22** [comment]
No, a prompt for password appeared out of the blue. I rememebred the backup button just after i pressed Return key…Wiadomość napisana przez Till Steinbach ***@***.***> w dniu 18.01.2023, o godz. 08:11:﻿
Did you change your password in Grafana?
Before you delete a volume, always do a backup of the data in the UI before. You can restore the backup afterwards.
