### ISSUE TITLE
Is it possible to suppress the login UI

### ISSUE THREAD

**Issue by thgau** [tillsteinbach/VWsFriend#414]
I protect the access to VWsFriend in my installation with the help of a client certificate and a traefik proxy in front of VWsFriend.
Therefore I would like to avoid the login page. Is there an easy way to do that? e.g. passing the the expected username/password via Basic Authentication or similar HTTP Header sent by the proxy?
Thanks & Regards
thgau

**Comment by tillsteinbach** [comment]
For Grafana I don’t know, but the backend supports Basic Auth

**Comment by cmantsch** [comment]
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/grafana/

**Comment by jaedle** [comment]
I would also love the possibility to disable the login through configuration (i.e. an environment variable).

**Comment by tillsteinbach** [comment]
In the Docker compose in the section for Grafana in Environment you could try to add
```
GF_AUTH_ANONYMOUS_ENABLED=true
GF_AUTH_ORG_ROLE=viewer
GF_AUTH_DISABLE_LOGIN_FORM=true
```

**Comment by jaedle** [comment]
@tillsteinbach thanks for your feedback. Adding basic auth also works perfectly fine :+1:

**Comment by jaedle** [comment]
I was thinking about if this is something that could be documented. Do you have any opinion if you think that's a good idea?
