### ISSUE TITLE
Unknown attribute targetSOC

### ISSUE THREAD

**Issue by upelectric** [tillsteinbach/VWsFriend#428]
Hi,

I am getting lots of warnings about unknown targetSOC_pct. The car is a e-up. Vwsfriend version is 0.23.3

WARNING:departure_timers_status:/vehicles/WVWZZZAA1PDxxxxxx/domains/departureTimers/departureTimersStatus/timers/1: Unknown attribute targetSOC_pct with value 80

**Comment by tillsteinbach** [comment]
Thank you for reporting, this is already known and will be fixed in the next release.

**Comment by tillsteinbach** [comment]
Added in 0.23.4
