### ISSUE TITLE
Unable to initialize Vehicle Parameters

### ISSUE THREAD

**Issue by PsYkO54** [tillsteinbach/VWsFriend#430]
When trying to access the Vehicle Parameters (/settings/vehicle/database/VINXXX) page for the first time, I have the following error:

[21/Feb/2023 13:49:24] "GET /settings/vehicle/database/VINXXX HTTP/1.1" 500 -
2023-02-21T13:49:24+0000:ERROR:_internal:Error on request:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/opt/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/vwsfriend/ui/settings.py", line 128, in vehicleDBParameters
    form.primary_capacity.data = dbVehicle.settings.primary_capacity
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'primary_capacity'

**Comment by yngves** [comment]
Exact same issue seen here. Fresh 0.23.4 instance.

**Comment by tillsteinbach** [comment]
This is a bug. I will try to fix it asap. In the meantime it should be possible to install 0.23.3 initialize the settings and then update to 0.23.4

**Comment by tillsteinbach** [comment]
Can you try out 0.23.5 please?

**Comment by yngves** [comment]
Not quite there yet, it seems:

2023-02-22T16:24:04+0000:INFO:_internal:172.20.0.1 - - [22/Feb/2023 16:24:04] "GET /settings/vehicle/database/WVxxxx HTTP/1.1" 500 -
vwsfriend-vwsfriend-1   | 2023-02-22T16:24:04+0000:ERROR:_internal:Error on request:
vwsfriend-vwsfriend-1   | Traceback (most recent call last):
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 333, in run_wsgi
vwsfriend-vwsfriend-1   |     execute(self.server.app)
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 320, in execute
vwsfriend-vwsfriend-1   |     application_iter = app(environ, start_response)
vwsfriend-vwsfriend-1   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2551, in __call__
vwsfriend-vwsfriend-1   |     return self.wsgi_app(environ, start_response)
vwsfriend-vwsfriend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2531, in wsgi_app
vwsfriend-vwsfriend-1   |     response = self.handle_exception(e)
vwsfriend-vwsfriend-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
vwsfriend-vwsfriend-1   |     response = self.full_dispatch_request()
vwsfriend-vwsfriend-1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
vwsfriend-vwsfriend-1   |     rv = self.handle_user_exception(e)
vwsfriend-vwsfriend-1   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
vwsfriend-vwsfriend-1   |     rv = self.dispatch_request()
vwsfriend-vwsfriend-1   |          ^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
vwsfriend-vwsfriend-1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
vwsfriend-vwsfriend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
vwsfriend-vwsfriend-1   |     return current_app.ensure_sync(func)(*args, **kwargs)
vwsfriend-vwsfriend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   |   File "/opt/venv/lib/python3.11/site-packages/vwsfriend/ui/settings.py", line 119, in vehicleDBParameters
vwsfriend-vwsfriend-1   |     if current_app.db.session.bind.dialect.name == 'postgresql':
vwsfriend-vwsfriend-1   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vwsfriend-vwsfriend-1   | AttributeError: 'NoneType' object has no attribute 'dialect'

**Comment by yngves** [comment]
I pulled from edge now, and it works like a charm! Thanks!

**Comment by PsYkO54** [comment]
I confirm it's working now with 0.23.5
Thank you for fixing this so quickly!
