### ISSUE TITLE
ERROR: 2 matches found based on name: network pi_bridge is ambiguous

### ISSUE THREAD

**Issue by monojk** [tillsteinbach/VWsFriend#432]
For a few days I haven't been able to start due to
```
pi@rp4b:~ $ docker-compose --env-file ./myconfig.env up
ERROR: 2 matches found based on name: network pi_bridge is ambiguous
```
I have no clue about the location of the problem.

Previously it ran w/o problems. I haven't changed anything since.

**Comment by tillsteinbach** [comment]
Your docker has two networks called pi_bridge and docker-compose does not know which one to take

**Comment by monojk** [comment]
Still, I don't know how to find the problem. I use docker-compose.yml like from github: 
```
networks:
  bridge:
  backend:
```

**Comment by tillsteinbach** [comment]
You could try to delete unused networks with: `docker network prune`

**Comment by monojk** [comment]
Thanks. That helped.
