### ISSUE TITLE
On startup: problem when communicating with WeConnect / No user id provided

### ISSUE THREAD

**Issue by yngves** [tillsteinbach/VWsFriend#439]
As of last night, I am getting this when doing `docker-compose --env-file ./myconfig.env up`.

```
vwsfriend_1   | 2023-03-01T10:35:03+0000:INFO:vwsfriend_base:vwsfriend 0.23.7 (using WeConnect-python 0.54.1, WeConnect-mqtt 0.42.2)
vwsfriend_1   | 2023-03-01T10:35:03+0000:INFO:session_manager:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
vwsfriend_1   | 2023-03-01T10:35:05+0000:CRITICAL:vwsfriend_base:There was a problem when communicating with WeConnect. If this problem persists please open a bug report: No user id provided
vwsfriend_vwsfriend_1 exited with code 0
```

This happens on both my vwfriend instances, one that had been running fine until last night but that began failing when I restarted it, and a fresh one that I set up this morning.

**Comment by tillsteinbach** [comment]
Looks like you need to login at myvolkswagen and accept the terms and conditions

**Comment by yngves** [comment]
Aha. Thanks! I will add a note to the FAQ about this.

**Comment by yngves** [comment]
Re-accepted terms and conditions at mywolkswagen. Works now.

**Comment by danielnord** [comment]
@yngves I have the same issue but all terms and conditions are already accepted. Did you need to un-accept and then accept again at https://vwid.vwgroup.io/account?

```
vwsfriend_1   | 2023-12-07T07:51:37+0000:INFO:vwsfriend_base:vwsfriend 0.24.2 (using WeConnect-python 0.59.5, WeConnect-mqtt 0.48.3)
vwsfriend_1   | 2023-12-07T07:51:37+0000:INFO:session_manager:Could not use token from file /tmp/weconnect.token ([Errno 2] No such file or directory: '/tmp/weconnect.token')
```
