### ISSUE TITLE
Vehicle image loading from hardcoded IP in Grafana car overview dashboard

### ISSUE THREAD

**Issue by cmantsch** [tillsteinbach/VWsFriend#44]
The vehicle image (top left panel in car overview dashboard) is not loading due to a hardcoded IP

The image in said panel is specified to load from 10.11.5.123

VWsFriend/overview.json

**Comment by tillsteinbach** [comment]
I just merged your submission. Thanks for sharing your finding and contributing a patch!

**Comment by tillsteinbach** [comment]
Available in https://github.com/tillsteinbach/VWsFriend/releases/tag/v0.5.1
