### ISSUE TITLE
Detail of the battery per cell in Grafana

### ISSUE THREAD

**Issue by Julien4135** [tillsteinbach/VWsFriend#443]
Hello, by looking a little in Grafana, I saw that it was possible to have the information in our cells.
The only problem is that I unfortunately don't know much about Grafana.
Could someone here explain the manipulation to do to have something like that?

https://zupimages.net/up/23/09/6gea.png

**Comment by tillsteinbach** [comment]
Sorry, I don't really understand what you want to do.

**Comment by Julien4135** [comment]
I would like to create a table of the state of the battery per cell, which would allow me to calculate the SOH once charged to 100%.

**Comment by tillsteinbach** [comment]
There is no such information on the API. You can only get the SoC for the whole battery
