### ISSUE TITLE
Graphana UI error - Templating

### ISSUE THREAD

**Issue by amenychtas** [tillsteinbach/VWsFriend#446]
After updating to 0.23.8, I get the error `Template variable service failed Cannot read properties of undefined (reading 'fields')` at the following dashbords:
- Charges
- Charging Statistics
- Journeys
- Refueling

See the screenshot below:  
![image](https://user-images.githubusercontent.com/3939897/222802759-985a250e-75dc-472e-9caf-9bd880a7dbf5.png)

The error doesn't seem to affect the functionality. Also the rest dashboards work fine.

**Comment by tillsteinbach** [comment]
This is a grafana bug recently introduced. I will downgrade grafana and publish a 0.23.9

**Comment by amenychtas** [comment]
Indeed, 0.23.9 works fine. Thank you @tillsteinbach !!
