### ISSUE TITLE
No Car available

### ISSUE THREAD

**Issue by abeamstart** [tillsteinbach/VWsFriend#509]
<!doctype html> <html lang=en> <title>404 Not Found</title> <h1>Not Found</h1> <p>Vehicle with VIN WVGZZZE2ZPE0....... doesn&#39;t exist.</p>

**Comment by abeamstart** [comment]
O.K. liegt wohl an VW, beim Login ins Online-Portal:
_Volkswagen ID
Etwas ist schief gelaufen
Bitte versuchen Sie es erneut.

Wenn das Problem weiter besteht kontaktieren Sie den Volkswagen-Support.
Fehlercode: 0fa6787e-4d6a-460f-ae59-926dd156df2a-20230616-054901577_

**Comment by tillsteinbach** [comment]
Jo, größerer Ausfall im Backend heute.

**Comment by abeamstart** [comment]
Danke für die Rückmeldung, zum Glück nicht nur bei mir...

**Comment by abeamstart** [comment]
Seit eben funktioniert wieder alles...
