### ISSUE TITLE
WARNING:vwsfriend_base:Retrieval error during update. 

### ISSUE THREAD

**Issue by dazzzl** [tillsteinbach/VWsFriend#510]
Today, I got a lot of this warning.... every second one...

WARNING:vwsfriend_base:Retrieval error during update. Will try again after configured interval of 180s

and in the end:

023-06-16T09:07:16+0200:ERROR:weconnect:Failed to retrieve data for VIN XX: Could not fetch data. Status Code was: 502

server problems?

**Comment by tillsteinbach** [comment]
Yes, the servers are down.
