### ISSUE TITLE
An unsupported vehicleType: fuel was provided

### ISSUE THREAD

**Issue by MyGitIT** [tillsteinbach/VWsFriend#525]
Hallo Till, 

Noch eine Kleinigkeit ist mir aufgefallen :

`2023-07-21T15:47:34+0200:WARNING:addressable:/vehicles/... /trips/shortTerm/vehicleType: An unsupported vehicleType: fuel was provided, known values are [electric, hybrid, gasoline, petrol, diesel, cng, lpg, invalid, unknown car type] please report this as a bug`

**Comment by tillsteinbach** [comment]
Danke, füge ich hinzu.
