### ISSUE TITLE
Odometer data field not updated anymore...

### ISSUE THREAD

**Issue by Flo-63** [tillsteinbach/VWsFriend#529]
Since July 23rd, the 'Odometer' data is showing same value in all charge and trip records. I'm not aware that I changed anything in my setup... Any ideas?

Many thanks,

Flo

**Comment by tillsteinbach** [comment]
Did you get SW 3.2?

**Comment by Flo-63** [comment]
Yes, somewhat in June. After the update, it worked well for at least 6 weeks.

**Comment by tillsteinbach** [comment]
There are some users reporting that after the update the odometer does not show correctly anymore. Also not in the App and on the website.

**Comment by Flo-63** [comment]
I jist checked the app. Wrong value here, too...
So, I'll try to open an issue at VW. 
Sorry to bother you.

⁣BlueMail for Android herunterladen ​

**Comment by philipperequile** [comment]
VW fixed the problem yesterday evening.
