### ISSUE TITLE
Two unknown attributes

### ISSUE THREAD

**Issue by mattsve** [tillsteinbach/VWsFriend#567]
My ID.4 returns two unknown attributes, temperatureBatteryStatus at least sounds interesting.

> unknown attribute temperatureBatteryStatus with value {'value': {'carCapturedTimestamp': '2023-10-25T05:33:46.628Z', 'temperatureHvBatteryMin_K': '281.15', 'temperatureHvBatteryMax_K': '281.15'}} in domain measurements
> Unknown attribute fuelLevelStatus with value {'value': {'carCapturedTimestamp': '2023-10-25T05:33:48.089Z', 'currentSOC_pct': 80, 'primaryEngineType': 'electric', 'carType': 'electric'}} in domain measurements

**Comment by tillsteinbach** [comment]
Yes, very interesting! What software version is your car running?

**Comment by mattsve** [comment]
3.2

**Comment by tillsteinbach** [comment]
Ok, on my ID.3 with sw 3.0 I cannot see it yet. I will add the attributes soon and then release a new version. Will be interesting to plot DC charging performance in relation to battery temperatures.

**Comment by tillsteinbach** [comment]
I'm looking for a user who uses VWsFriend with HomeKit support to try out the new attributes. There should be now a new accessory in the Home App showing the battery temperature

**Comment by tillsteinbach** [comment]
Released with 0.24.0
