### ISSUE TITLE
Fetching data too often causes 429

### ISSUE THREAD

**Issue by korhojoa** [tillsteinbach/VWsFriend#578]
It seems vwsfriend is requesting data too often?
First there was a bad gateway error, and after that it tries to query with ~3½ minute intervals, which I guess is too often, and then it gets rate limited.
```
vwsfriend-vwsfriend-1  | 2023-11-12T14:42:21+0000:INFO:vwsfriend_base:Updating data from WeConnect
vwsfriend-vwsfriend-1  | 2023-11-12T14:42:24+0000:WARNING:vehicle:/vehicles/WVWZZZAUZEW901234: Unknown attribute temperatureBatteryStatus with value {'error': {'message': 'Bad Gateway', 'errorTimeStamp': '2023-11-12T14:42:24Z', 'info': 'Upstream service responded with an unexpected status. If the problem persists, please contact our support.', 'code': 4105, 'group': 2, 'retry': True}} in domain measurements
vwsfriend-vwsfriend-1  | 2023-11-12T14:42:24+0000:WARNING:vehicle:/vehicles/WVWZZZAUZEW901234: Unknown attribute fuelLevelStatus with value {'error': {'message': 'Bad Gateway', 'errorTimeStamp': '2023-11-12T14:42:24Z', 'info': 'Upstream service responded with an unexpected status. If the problem persists, please contact our support.', 'code': 4105, 'group': 2, 'retry': True}} in domain measurements
...
vwsfriend-vwsfriend-1  | 2023-11-12T16:20:57+0000:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZKW901234: Could not fetch data. Status Code was: 429
vwsfriend-vwsfriend-1  | 2023-11-12T16:23:30+0000:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZEW901234: Could not fetch data. Status Code was: 429
vwsfriend-vwsfriend-1  | 2023-11-12T16:23:31+0000:INFO:abrp_agent:ABRP send telemetry {'is_parked': False, 'odometer': 53550, 'is_charging': False} for vehicle WVWZZZAUZKW901234 for account u@f.com: Missing telemetry: utc, soc, power, speed, lat, lon,
vwsfriend-vwsfriend-1  | 2023-11-12T16:24:21+0000:INFO:vwsfriend_base:Updating data from WeConnect
vwsfriend-vwsfriend-1  | 2023-11-12T16:26:56+0000:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZEW901234: Could not fetch data. Status Code was: 429
vwsfriend-vwsfriend-1  | 2023-11-12T16:29:29+0000:ERROR:weconnect:Failed to retrieve data for VIN WVWZZZAUZKW901234: Could not fetch data. Status Code was: 429
```

**Comment by tillsteinbach** [comment]
This can happen if the interval is too low or you use other apps that query the API too often. Only thing you can do is reduce the interval.

**Comment by korhojoa** [comment]
I would assume the correct way to fix this is to handle the 429 and then change the interval.
I'm using the default setting and don't have any other things that query the API (excluding phone app, which incidentally is how I know that it's giving a 429, since the phone app seems to show absolutely no data when that happens).

The default is clearly too aggressive, since it gets itself locked out without me ever using the app. I mostly just look at grafana, and noticed this after there were no updates for a while.

**Comment by tillsteinbach** [comment]
> I would assume the correct way to fix this is to handle the 429 and then change the interval. I'm using the default setting and don't have any other things that query the API (excluding phone app, which incidentally is how I know that it's giving a 429, since the phone app seems to show absolutely no data when that happens).

The problem is, what is the correct interval? It depends on what the user is doing with the phone app and other tools.
It also seems that the interval is per vehicle, so if you have two vehicles it can happen that for one you see the 429 for the other not. The limit for ID cars seems much more relaxed.

> The default is clearly too aggressive, since it gets itself locked out without me ever using the app. I mostly just look at grafana, and noticed this after there were no updates for a while.

Yes, I changed the default to 300 now what seems to work.

> EDIT: Also, seeing as this was triggered by something in VW's stack failing to work, then excessive queries are sent, I think that there is a failure in some exception handling. If the backend service responds with garbage, there should be some kind of consideration to not throw more queries at it before it starts responding well to queries. This would also help with account lockouts when the API changes.

When 429 is responded there are no new queries for the next 15min.
