### ISSUE TITLE
Neues Release für PyPi

### ISSUE THREAD

**Issue by MyGitIT** [tillsteinbach/VWsFriend#583]
Hallo Steini,

kannst du bitte mal ein neues Release für PyPi erstellen?

Gruß Sven

**Comment by tillsteinbach** [comment]
Ich suche noch jemanden der eine Installation mit HomeKit und ein Auto mit Batterietemperatur hat und einmal testen würde bevor ich ein release mache. Aber wenn sich da niemand findet mache ich ein release und dann muss ich zur not die Fehler patchen wenn sie gemeldet werden.

**Comment by MyGitIT** [comment]
Meinst du die HV Temperatur? 

Timestamp': '2023-11-17T14:51:13.54Z', 'temperatureHvBatteryMin_K': '284.65', 'temperatureHvBatteryMax_K': '285.15'}} in domain measurements

**Comment by tillsteinbach** [comment]
Jo, die Temperatur sollte mit dem aktuellen Master in der Apple Home App angezeigt werden

**Comment by MyGitIT** [comment]
Okay, bei Apple bin ich raus, Linux/Android Jünger 😊

**Comment by tillsteinbach** [comment]
Da hoffe ich ja noch auf Matter, wenn es da was gutes für Python gibt dann würde ich die SmartHome Integration umstellen sodass die Android Nutzer auch was von haben...

**Comment by tillsteinbach** [comment]
Habe mal die 0.24.0 released
