### ISSUE TITLE
python 3.12 

### ISSUE THREAD

**Issue by rhege123** [tillsteinbach/VWsFriend#585]
seit dem Update auf 0.24.0 im docker geht der Container nach kurzer Zeit in den Fehler
Exception occurred during processing of request from ('127.0.0.1', 59170)
Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 706, in process_request
    t.start()
  File "/usr/lib/python3.12/threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

Nach einem Restart des Container läuft alles erstmal einige Minuten, bis der Fehler erneut auftritt.

**Comment by ra2806** [comment]
Kann ich bestätigen. Hast Du Homekit-Support aktiviert, also in den ADDITIONAL_PARAMETERS "--with-homekit" verwendet? Dann lass das mal weg. Bei mir klappt es anscheinend dann wieder (aber eben ohne homekit)

@tillsteinbach  Hier noch die Meldung bevor die o.g. Fehler protokolliert werden:

^[[32mvwsfriend_1   |^[[0m 2023-11-27T16:27:50+0000:INFO:weconnect_mqtt_base:Client successfully disconnected
^[[32mvwsfriend_1   |^[[0m Traceback (most recent call last):
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/bin/vwsfriend", line 8, in <module>
^[[32mvwsfriend_1   |^[[0m     sys.exit(main())
^[[32mvwsfriend_1   |^[[0m 2023-11-27T16:27:50+0000:ERROR:vwsfriend_base:MQTT Connection failed
^[[32mvwsfriend_1   |^[[0m              ^^^^^^
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/vwsfriend/vwsfriend_base.py", line 516, in main
^[[32mvwsfriend_1   |^[[0m     mqttCLient.updateWeConnect(reraise=True)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 469, in updateWeConnect
^[[32mvwsfriend_1   |^[[0m     self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 194, in update
^[[32mvwsfriend_1   |^[[0m     self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 221, in updateVehicles
^[[32mvwsfriend_1   |^[[0m     self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures,
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/elements/vehicle.py", line 226, in update
^[[32mvwsfriend_1   |^[[0m     self.updateStatus(updateCapabilities=updateCapabilities, force=force, selective=selective)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/elements/vehicle.py", line 350, in updateStatus
^[[32mvwsfriend_1   |^[[0m     self.domains[domain.value][key].update(fromDict=data[domain.value][key])
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/elements/temperature_battery_status.py", line 28, in update
^[[32mvwsfriend_1   |^[[0m     self.temperatureHvBatteryMin_K.fromDict(fromDict['value'], 'temperatureHvBatteryMin_K')
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 309, in fromDict
^[[32mvwsfriend_1   |^[[0m     self.setValueWithCarTime(float(fromDict[key]), lastUpdateFromCar=None, fromServer=True)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 248, in setValueWithCarTime
^[[32mvwsfriend_1   |^[[0m     self.notify(flags)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 78, in notify
^[[32mvwsfriend_1   |^[[0m     observer(element=self, flags=flags)
**^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/vwsfriend/homekit/battery_temperature.py", line 92, in onBatteryTemperatureChange
^[[32mvwsfriend_1   |^[[0m     if flags & AddressableLeaf.ObserverEvent.VALUE_CHANGED and element.temperatureHvBatteryMin_K.enabled and element.temperatureHvBatteryMax_K.enabled:
^[[32mvwsfriend_1   |^[[0m                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[32mvwsfriend_1   |^[[0m AttributeError: 'AddressableAttribute' object has no attribute 'temperatureHvBatteryMin_K'**
^[[32mvwsfriend_1   |^[[0m ----------------------------------------
^[[32mvwsfriend_1   |^[[0m Exception occurred during processing of request from ('127.0.0.1', 60318)
^[[32mvwsfriend_1   |^[[0m Traceback (most recent call last):
^[[32mvwsfriend_1   |^[[0m   File "/usr/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
^[[32mvwsfriend_1   |^[[0m     self.process_request(request, client_address)
^[[32mvwsfriend_1   |^[[0m   File "/usr/lib/python3.12/socketserver.py", line 706, in process_request
^[[32mvwsfriend_1   |^[[0m     t.start()
^[[32mvwsfriend_1   |^[[0m   File "/usr/lib/python3.12/threading.py", line 971, in start
^[[32mvwsfriend_1   |^[[0m     _start_new_thread(self._bootstrap, ())
^[[32mvwsfriend_1   |^[[0m RuntimeError: can't create new thread at interpreter shutdown
^[[32mvwsfriend_1   |^[[0m ----------------------------------------

**Comment by rhege123** [comment]
Ja, habe ich. Das hilft mir schonmal sehr weiter. Bin gerade im Urlaub und werd dann erstmal das homekit deaktivieren. Danke für den schnellen Support. ------ gesendet mobile ------Am 28.11.2023 um 16:11 schrieb ra2806 ***@***.***>:﻿
Kann ich bestätigen. Hast Du Homekit-Support aktiviert, also in den ADDITIONAL_PARAMETERS "--with-homekit" verwendet? Dann lass das mal weg. Bei mir klappt es anscheinend dann wieder (aber eben ohne homekit)
@tillsteinbach  Hier noch die Meldung bevor die o.g. Fehler protokolliert werden:
^[[32mvwsfriend_1   |^[[0m 2023-11-27T16:27:50+0000:INFO:weconnect_mqtt_base:Client successfully disconnected
^[[32mvwsfriend_1   |^[[0m Traceback (most recent call last):
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/bin/vwsfriend", line 8, in 
^[[32mvwsfriend_1   |^[[0m     sys.exit(main())
^[[32mvwsfriend_1   |^[[0m 2023-11-27T16:27:50+0000:ERROR:vwsfriend_base:MQTT Connection failed
^[[32mvwsfriend_1   |^[[0m              ^^^^^^
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/vwsfriend/vwsfriend_base.py", line 516, in main
^[[32mvwsfriend_1   |^[[0m     mqttCLient.updateWeConnect(reraise=True)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect_mqtt/weconnect_mqtt_base.py", line 469, in updateWeConnect
^[[32mvwsfriend_1   |^[[0m     self.weConnect.update(updateCapabilities=self.updateCapabilities, updatePictures=self.updatePictures, selective=self.selective, force=True)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 194, in update
^[[32mvwsfriend_1   |^[[0m     self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/weconnect.py", line 221, in updateVehicles
^[[32mvwsfriend_1   |^[[0m     self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures,
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/elements/vehicle.py", line 226, in update
^[[32mvwsfriend_1   |^[[0m     self.updateStatus(updateCapabilities=updateCapabilities, force=force, selective=selective)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/elements/vehicle.py", line 350, in updateStatus
^[[32mvwsfriend_1   |^[[0m     self.domains[domain.value][key].update(fromDict=data[domain.value][key])
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/elements/temperature_battery_status.py", line 28, in update
^[[32mvwsfriend_1   |^[[0m     self.temperatureHvBatteryMin_K.fromDict(fromDict['value'], 'temperatureHvBatteryMin_K')
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 309, in fromDict
^[[32mvwsfriend_1   |^[[0m     self.setValueWithCarTime(float(fromDict[key]), lastUpdateFromCar=None, fromServer=True)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 248, in setValueWithCarTime
^[[32mvwsfriend_1   |^[[0m     self.notify(flags)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/weconnect/addressable.py", line 78, in notify
^[[32mvwsfriend_1   |^[[0m     observer(element=self, flags=flags)
^[[32mvwsfriend_1   |^[[0m   File "/opt/venv/lib/python3.12/site-packages/vwsfriend/homekit/battery_temperature.py", line 92, in onBatteryTemperatureChange
^[[32mvwsfriend_1   |^[[0m     if flags & AddressableLeaf.ObserverEvent.VALUE_CHANGED and element.temperatureHvBatteryMin_K.enabled and element.temperatureHvBatteryMax_K.enabled:
^[[32mvwsfriend_1   |^[[0m                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[32mvwsfriend_1   |^[[0m AttributeError: 'AddressableAttribute' object has no attribute 'temperatureHvBatteryMin_K'
^[[32mvwsfriend_1   |^[[0m ----------------------------------------
^[[32mvwsfriend_1   |^[[0m Exception occurred during processing of request from ('127.0.0.1', 60318)
^[[32mvwsfriend_1   |^[[0m Traceback (most recent call last):
^[[32mvwsfriend_1   |^[[0m   File "/usr/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
^[[32mvwsfriend_1   |^[[0m     self.process_request(request, client_address)
^[[32mvwsfriend_1   |^[[0m   File "/usr/lib/python3.12/socketserver.py", line 706, in process_request
^[[32mvwsfriend_1   |^[[0m     t.start()
^[[32mvwsfriend_1   |^[[0m   File "/usr/lib/python3.12/threading.py", line 971, in start
^[[32mvwsfriend_1   |^[[0m     _start_new_thread(self._bootstrap, ())
^[[32mvwsfriend_1   |^[[0m RuntimeError: can't create new thread at interpreter shutdown
^[[32mvwsfriend_1   |^[[0m ----------------------------------------

**Comment by tillsteinbach** [comment]
In approximate an hour there will be a 0.24.1 that hopefully resolves this. Unfortunately I don't have a car with battery temperature to test with

**Comment by ra2806** [comment]
Dankeschön. Sieht gut aus!

**Comment by tillsteinbach** [comment]
Hmmm, hier funktioniert mqtt 5 noch. Komisch.

hast du in HomeKit jetzt auch die Batterietemperatur?

**Comment by rhege123** [comment]
Die Batterietemperatur kommt in HomeKit an.
Allerdings tritt der Fehler bei mir immer noch auf. 
Habe allerdings auch noch mqtt aktiv.
  File "/opt/venv/lib/python3.12/site-packages/vwsfriend/homekit/battery_temperature.py", line 96, in onBatteryTemperatureChange
2023-11-28T20:39:56+0100:ERROR:vwsfriend_base:MQTT Connection failed
    observer(element=self, flags=flags)
    self.setChargingState(self.batteryTemperatureStatus.temperatureHvBatteryMin_K.value, self.batteryTemperatureStatus.temperatureHvBatteryMax_K.value)
TypeError: BatteryTemperature.setChargingState() takes 2 positional arguments but 3 were given

**Comment by tillsteinbach** [comment]
oh man, ja, dann noch ein versuch mit 0.24.2 ... echt schwierig ohne so ein Auto das zu testen.

Das sollte mit MQTT nichts zutun haben. Das MQTT Connection failed sagt eigentlich nur dass er keine Verbindung zum Broker bekommt.
