### ISSUE TITLE
Log timestamp missing

### ISSUE THREAD

**Issue by MattiJarvinen** [tillsteinbach/VWsFriend#59]
Python logging is a bit new to me but shouldn't this be?

`format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s  `

https://github.com/tillsteinbach/VWsFriend/blob/2354edebe22f7801f157e95bcc658bc3f23a1223/vwsfriend/vwsfriend/model/alembic.ini#L99

**Comment by tillsteinbach** [comment]
The line you pasted is just the configuration for the part that updates the database schema.
I'm thinking whether to add the time to the log output or make the logging output format in general configurable as a commandline argument.

**Comment by tillsteinbach** [comment]
With release 0.6.0 time is added to log output and in general the log output format can be adjusted using `--logging-date-format`
