### ISSUE TITLE
CO2 offset rescued trees

### ISSUE THREAD

**Issue by claesto** [tillsteinbach/VWsFriend#602]
[Tronity](https://app.tronity.io/dashboard) has what I think a _fun_ feature, informing you about the saved CO2 because of driving an EV. [screenshot](https://imgur.com/a/llzaS4S)

I did some _research_ and apparently there are formulas available to calculate this, based on the country you're in but most seem to revolve around this formula:

`trees planted = <kWh produced> * <trees planted factor>` which is for most countries `0.0117`.

I'm not entirely sure where each number comes from. I know they assign a certain co2 kg measurement to each trip you make, and each charging session as well. The charging sessions combined equal the **4kg**. I don't know how they get to the **78kg** saved. I thought maybe they get that somehow from your _trips_ but it's only **2kg**.

I saw that they somewhere in their code use the following formula:

`${Math.round(12 / 1700 * e.status.charges.co2Saved)}` to get to trees saved and one endpoint returns these results:

```
{
    "kWh": 27.839999999999996,
    "total": 2,
    "totalNoCardId": 2,
    "max": 0,
    "co2": 4,
    "co2Saved": 78,
    "dc": 0,
    "ac": 27.839999999999996,
    "cost": null
}
```

So would it be feasible to include a "trees rescued" statistic/feature on the **charging statistics** dashboard?

**Comment by tillsteinbach** [comment]
I'm not sure if I want to go that path. It feels a bit like greenwashing saying you saved CO2 by driving. Most CO2 is saved when you do not drive at all

**Comment by cmantsch** [comment]
@claesto If you want to have that in the dashboard, you can add it by yourself. Grafana panels are quite easy to create, especially when you can just copy another one and just modify that for your needs
