### ISSUE TITLE
An unsupported chargeType: unsupported was provided, known values are [invalid, off, ac, dc, unknown charge type] please report this as a bug

### ISSUE THREAD

**Issue by MyGitIT** [tillsteinbach/VWsFriend#634]
Seit einigen Tagen kommt bei mir folgender Fehler :

An unsupported chargeType: unsupported was provided, known values are [invalid, off, ac, dc, unknown charge type] please report this as a bug

Keine Ahnung warum, sonst funktioniert eigentlich alles.

Gruß Sven

**Comment by tillsteinbach** [comment]
Should be fixed in 0.24.5
