### ISSUE TITLE
Define URL for usage behind reverse proxy

### ISSUE THREAD

**Issue by malwikl** [tillsteinbach/VWsFriend#652]
Hi all,

I setup the project on my private docker instance and want to use it behind a reverse proxy with an external URL. this works well, except the URL for the jumpins in the dashboard like "Car Settings", "Edit charging session"...
The URL's point to http://192.168.178.3:3000/... which is of course not accesible outside the reverse proxy.

Is there a way to define the hostname during setup or the env file?

Thanks,
MAlWiKl

**Comment by tillsteinbach** [comment]
You can change it through the webinterface here:

http://192.168.178.3:4000/database/settings/edit

IP/Port to be adapted according your setup
