### ISSUE TITLE
unsupported chargingScenario: immediatelyChargingFinished - please report this as a bug

### ISSUE THREAD

**Issue by newmy-de** [tillsteinbach/VWsFriend#655]
Just found this in my logs:

WARNING:addressable:/vehicles/WVGZZZE2ZPP51XXXX/domains/charging/chargingStatus/chargingScenario: An unsupported chargingScenario: immediatelyChargingFinished was provided, known values are [off, unknown charge type] please report this as a bug

regards
Ulrich

**Comment by tillsteinbach** [comment]
Hi Ulrich,
thank you for reporting. This is already fixed in the repo and will be available with the next release.

**Comment by WerFra** [comment]
There are more charging scenarios currently producing warnings: chargingToDepartureTimeWaiting, chargingToDepartureTimeActive, optimisedChargingFinished
Are these also fixed?

**Comment by tillsteinbach** [comment]
thanks for reporting will add those too

**Comment by tillsteinbach** [comment]
fixed in 0.24.6
