### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by motorto** [tillsteinbach/VWsFriend#668]
Hi, thanks for the awesome project. 

I deployed it last night, and I have some questions.

The dashboard seemed to show the car charging (as shown in the print screen below), but when I go to vwsfriends and list chargings, I get none. Do I need to add them manually?

![image](https://github.com/user-attachments/assets/e15fbe6c-c4f2-4e0c-b63e-4fe4a0c81824)

Sorry for the beginner questions; I didn't find a quick-start guide or any info in the FAQ (I can help with that if needed).

**Comment by tillsteinbach** [comment]
No, those should appear automatically.

**Comment by motorto** [comment]
Do they only appear after I unplug the charger, maybe ?

**Comment by tillsteinbach** [comment]
No, they should appear right away. Can you check the log for errors?

**Comment by motorto** [comment]
Sure, could you please tell me how I get them ? New to the container world

**Comment by motorto** [comment]
The car might already be charging when I finished setting it up let me try to put it charging during the day and stopping again.

**Comment by motorto** [comment]
Yeah, it is working fine !! 

It happened because when I finished the setup, it was already charging.


Is there a way to increase the update frequency (or force a manual update) ?
