### ISSUE TITLE
postgresdatabase not working properly

### ISSUE THREAD

**Issue by Worschtbrot** [tillsteinbach/VWsFriend#680]
Hello all,
I receive an error message when trying to start the docker containers with the docker compose command:

(psycopg2.OperationalError) connection to server at "postgresdbbackend" (172.20.0.3), port 5432 failed: FATAL:  password authentication failed for user "admin"
The postgres container starts, but I am not able to access the database from the container console either....

Did I miss something in the config?

**Comment by motorto** [comment]
I'm having the same issue. An update pushed to the postgres:13 image in the docker hub is causing the problem. Everything was working fine previously, but I tried to deploy it on another system and now have this issue.

```
vwsfriend-1  | 2024-10-20T23:44:47+0000:ERROR:agent_connector:Could not establish a connection to database, will try again after 10 seconds: (psycopg2.OperationalError) connection to server at "postgresdbbackend" (172.27.0.2), port 5432 failed: FATAL:  password authentication failed for user "admin"
vwsfriend-1  | 
vwsfriend-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

```
postgresdb-1  | 2024-10-20 23:50:17.335 UTC [485] FATAL:  password authentication failed for user "admin"
postgresdb-1  | 2024-10-20 23:50:17.335 UTC [485] DETAIL:  Password does not match for user "admin".
postgresdb-1  | 	Connection matched pg_hba.conf line 99: "host all all all md5"
```

**Comment by Worschtbrot** [comment]
Hello, thank you for your replay. Unfortunately, the error stays the same....

**Comment by Worschtbrot** [comment]
Perfect. Deleting the volumes did the trick! Thank you so much!

**Comment by motorto** [comment]
Close the issue, problem solved
