### ISSUE TITLE
Journey information?

### ISSUE THREAD

**Issue by ualex73** [tillsteinbach/VWsFriend#687]
I just installed vwsfriend and I can see a lot of information in the grafana interface … I see a journey(s) option, but this stays empty? Is there a way to enable it?
Btw In the Volkswagen app I do not see journey option at this moment?

**Comment by tillsteinbach** [comment]
This will fill when you drive. When you want to have an overview over journeys you did adapt the timespan of your journey:
<img width="1151" alt="Bildschirmfoto 2024-11-04 um 15 45 28" src="https://github.com/user-attachments/assets/df6d6e1e-8a6f-45d3-ad11-e212e731416a">
afterwards you can press the "trim" button to exactly match the first/last trip.
<img width="1151" alt="Bildschirmfoto 2024-11-04 um 15 46 31" src="https://github.com/user-attachments/assets/3fd99bc7-dc69-4bbf-a960-7375f7f9d25c">

If you are happy with the result press "Add journey" to store your Journey on the "journey" page to retrieve it as often as you like.

**Comment by ualex73** [comment]
Is there a possibility to auto fill this? Currently it stays empty on my side ... I am running SW 5.0.

**Comment by tillsteinbach** [comment]
what do you mean with autofill?

**Comment by ualex73** [comment]
That trips are automatically recorded in the vwsfriend app when I have driven. Currently I cannot see any trip in the app, so I am in doubt it works.

**Comment by ualex73** [comment]
Interesting, the trip recorded only started to work on 13-Nov. Before that date (account is then already 2 weeks active), nothing happens.
