### ISSUE TITLE
Backup 0.9.0 schlägt fehl

### ISSUE THREAD

**Issue by gbmd** [tillsteinbach/VWsFriend#82]
Hi Till,
habe meine container gerade geupdated von 0.6.0 auf 0.9.0 (mit docker-compose pull)
Leider funktioniert die Backupfunktion nicht. Folgende Fehlermeldung (und code 500 Internal server error):
```Internal Server Error
pg_dump returned 1: pg_dump: error: server version: 13.4 (Debian 13.4-4.pgdg110+1); pg_dump version: 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
pg_dump: error: aborting because of server version mismatch```

in der db sind noch alle alten daten drin, das ist so weit kein problem.

VG und Danke!

**Comment by tillsteinbach** [comment]
Ach Mist! Hab ich geschlafen! Ich baue so schnell wie möglich ein Update.

**Comment by tillsteinbach** [comment]
0.9.1 ist released, kannst du schauen ob es gefixt ist?
